### ISSUE TITLE
question about the multi-dimension of the input x

### ISSUE THREAD

**Issue by TFLQW** [Magica-Chen/gptp_multi_output#3]
I have read your blog in zhihu, so i have tried your code, thanks for your contribution. but i notice that your input dimension is 1,so i want to input about 2 or 4 dimension of x, i made some change but it have problems, i wonder whether your code can achieve the multi-input as well as multi-output. 

出错 gptp_general>@(hyp,x,z)covfunc(hyp,x,z,i) (line 114)
    dk{i} = @(hyp,x,z) covfunc(hyp,x,z,i);

出错 mvgp_solve_gpml (line 166)
            dK = dk{j}(bsxfun(@minus,x(:),x(:)'),para_kernel);

出错 gptp_general>@(w)funcGP(w,xtr,ytr,k,dk) (line 268)
                [~,nlml_gp_new] = fminunc(@(w) funcGP(w,xtr,ytr,k,dk), ...

出错 fminunc (line 276)
        [f,GRAD] = feval(funfcn{3},x,varargin{:});

出错 gptp_general/gp_part (line 268)
                [~,nlml_gp_new] = fminunc(@(w) funcGP(w,xtr,ytr,k,dk), ...

出错 gptp_general (line 159)
                mvGPpredictor = gp_part(xtr, ytr, xte, d_input,d_target,...

出错 MV_gpr_ur (line 71)
[mGPpredictor] = gptp_general(...

原因:
    Failure in initial objective function evaluation. FMINUNC cannot continue.

**Comment by Magica-Chen** [comment]
Did you use the correct kernel, saying covSEard rather than covSEiso?

**Comment by Magica-Chen** [comment]
I added an example for 2-d input

**Comment by TFLQW** [comment]
> 
> 
> Did you use the correct kernel, saying covSEard rather than covSEiso?
thanks for your help i have solved that problem
