### ISSUE TITLE
hello,Chen,I have some question about my program.I don't know how to solve it

### ISSUE THREAD

**Issue by CloudCutter** [Magica-Chen/gptp_multi_output#6]
[gptp_multi_output-master-知乎.zip](https://github.com/Magica-Chen/gptp_multi_output/files/5729073/gptp_multi_output-master-.zip)
My data doesn't fit well into this program，I tune so many hyperparameter and the result is not satisfactory. Can you help me?Appreciate it!

**Comment by Magica-Chen** [comment]
I'm sorry I don't know how to tune parameters for you because I have no experience with your given dataset.
